---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  labels:
    app: simple-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: hashicorp/http-echo
        args:
          - "-text=Hello from simple-http-server"
        ports:
          - containerPort: 5678
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-server
spec:
  selector:
    app: simple-http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server-error
  labels:
    app: simple-http-server-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server-error
  template:
    metadata:
      labels:
        app: simple-http-server-error
    spec:
      containers:
      - name: simple-http-server
        image: hashicorp/http-echo
        args:
          - "-text=Hello from simple-http-server-error"
        ports:
          - containerPort: 5678
        readinessProbe:
          httpGet:
            path: /
            port: 5677
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5677
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-server-error
spec:
  selector:
    app: simple-http-server-error
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
---


